<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>throw command</title>
<link rel="stylesheet" type="text/css" href="style.css">
<meta name="generator" content="DocBook XSL Stylesheets Vsnapshot">
</head>
<body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="section">
<div class="titlepage">
<div><div><h2 class="title" style="clear: both">
<a name="throw_command" target="_self"></a>throw command</h2></div></div>
<hr>
</div>
<div class="simplesect">
<div class="titlepage"><div><div><h3 class="title">
<a name="gen-000" target="_self"></a>Usage</h3></div></div></div>
<p><code class="literal">throw <a class="ulink" href="s_exp.html" target="_self">expression</a></code></p>
</div>
<div class="simplesect">
<div class="titlepage"><div><div><h3 class="title">
<a name="gen-001" target="_self"></a>Description</h3></div></div></div>
<p>
	    This command throws and exception containing error message
	    given by the obligatory <a class="ulink" href="s_exp.html" target="_self">expression</a>
	    argument. If the exception is not handled 
	    by some surrounding <a class="ulink" href="s_try_catch.html" target="_self">try</a> block,
	    the execution is stopped immediately and the error
	    message is printed.
	  </p>
</div>
<div class="simplesect">
<div class="titlepage"><div><div><h3 class="title">
<a name="gen-002" target="_self"></a>See Also</h3></div></div></div>
<p><a class="ulink" href="s_try_catch.html" target="_self">try</a></p>
</div>
<div class="simplesect">
<div class="titlepage"><div><div><h3 class="title">
<a name="gen-003" target="_self"></a>Sections</h3></div></div></div>
<p><a class="ulink" href="s_Flow.html" target="_self">Flow control</a></p>
</div>
</div></body>
</html>
